// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Let the developer or users configure their database dynamically via browser tools or a settings panel.
const DEFAULT_SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "";
const DEFAULT_SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "";

const SUPABASE_URL = localStorage.getItem("OVERRIDE_SUPABASE_URL") || DEFAULT_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = localStorage.getItem("OVERRIDE_SUPABASE_PUBLISHABLE_KEY") || DEFAULT_SUPABASE_PUBLISHABLE_KEY;

// Guard with generic/dummy values if empty to prevent application-wide crash on startup
const finalUrl = SUPABASE_URL || "https://placeholder-project-id.supabase.co";
const finalKey = SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.dummy-placeholder-key";

export const supabase = createClient<Database>(finalUrl, finalKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
